version: 2
machine:
  timezone:
    America/Denver
  node:
    version: 8
  services:
    - rabbitmq-server
general:
  artifacts:
    - "coverage"
dependencies:
  pre:
    - rm -rf node_modules/
deployment:
  release:
    tag: /v.*/
    owner: twindagger
    commands:
      - npm publish
test:
  override:
    - npm run ci
