version: 2
jobs:
  build:
    working_directory: ~/magicbus
    docker:
      - image: node:8
      - image: rabbitmq:3
    steps:
      - checkout
      - run:
          name: dependencies
          command: npm install
      - run:
          name: install-junit-reporter
          command: npm install mocha-junit-reporter
      - run:
          name: test
          command: npm run ci
          environment:
            MOCHA_REPORTER: mocha-junit-reporter
            MOCHA_FILE: /tmp/tests/junit/test-results.xml
      - store_test_results:
          path: /tmp/tests
      - store_artifacts:
          path: test-results.xml
  deploy:
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
        name: store-token
        command: echo //registry.npmjs.org/:_authtoken=$NPM_AUTH_TOKEN > ./.npmrc
      - run:
          name: dependencies
          command: npm install
      - run:
        name: publish
        command: npm publish
workflows:
  version: 2
  build-workflow:
    - build:
        filters:
          tags:
            only: /.*/
    - deploy:
        requires:
          - build
        filters:
          tags:
            only: /v\d+\.\d+(\.\d+)?(-.*)?/
          branches:
            ignore: /.*/
