version: 2
jobs:
  build:
    working_directory: ~/magicbus
    docker:
      - image: node:16
      - image: rabbitmq:3
    steps:
      - checkout
      - run:
          name: dependencies
          command: npm install
      - run:
          name: test
          command: npm run ci
          environment:
            JEST_JUNIT_OUTPUT: /tmp/tests/junit/test-results.xml
      - store_test_results:
          path: /tmp/tests
  deploy:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: store-token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
      - run:
          name: dependencies
          command: npm install
      - run:
          name: publish
          command: npm publish
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v\d+\.\d+(\.\d+)?(-.*)?/
            branches:
              ignore: /.*/
