version: 2
jobs:
  build:
    working_directory: ~/magicbus
    docker:
      - image: node:8
      - image: rabbitmq:3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run ci
      - store_test_results:
          path: test-results.xml
          prefix: tests
